title: Observatoire Sans Tête
repository: gehelem/ost-documentation
description: >-
  Observatoire Sans Tête - Description
baseurl: /
url: 'https://documentation.ostserver.fr'
plugins:
  - jekyll-default-layout
  - jekyll-remote-theme
github_username: gehelem
domain: documentation.ostserver.fr
remote_theme: pages-themes/dinky@v0.2.0


